[package]
name = "graph-builder"
version = "0.1.0"
authors = ["Alex Crawford <crawford@redhat.com>"]
edition = "2018"
build = "src/build.rs"

[dependencies]
actix = "^0.9"
actix-web = "^2.0"
chrono = "^0.4.7"
cincinnati = { path = "../cincinnati" }
commons = { path = "../commons" }
env_logger = "^0.6.0"
flate2 = "^1.0.1"
futures = "0.3"
itertools = "^0.8.2"
lazy_static = "^1.2.0"
log = "^0.4.3"
prometheus = { git = "https://github.com/pingcap/rust-prometheus.git", rev = "6a02b0d2943f8fffce672e236e22c6f925184d93"}
quay = { path = "../quay" }
regex = "^1.1.0"
reqwest = "^0.10"
semver = { version = "^0.9.0", features = [ "serde" ] }
serde = "^1.0.70"
serde_derive = "^1.0.70"
serde_json = "^1.0.22"
smart-default = "^0.5.1"
structopt = "^0.2.10"
tar = "^0.4.16"
tokio = { version = "0.2.11", features = [ "fs", "stream" ] }
toml = "^0.4.10"
url = "^1.7.2"
parking_lot = "^0.8.0"
tempfile = "^3.1.0"
async-trait = "^0.1"
custom_debug_derive = "^0.1.7"
opentelemetry = "0.4.0"
actix-service = "1.0.0"

[build-dependencies]
built = "^0.3.2"

[dev-dependencies]
twoway = "^0.2"

[features]
test-net = []
test-net-private = []
