[package]
name = "graph-builder"
version = "0.1.0"
authors = ["Alex Crawford <crawford@redhat.com>"]
edition = "2018"
build = "src/build.rs"

[dependencies]
actix = "^0.10"
actix-web = "^2.0"
chrono = "^0.4.7"
cincinnati = { path = "../cincinnati" }
commons = { path = "../commons" }
env_logger = "^0.8"
flate2 = "^1.0.1"
futures = "0.3"
itertools = "^0.10"
lazy_static = "^1.2.0"
log = "^0.4.3"
prometheus = "0.9"
quay = { path = "../quay" }
regex = "^1.1.0"
reqwest = "^0.10"
semver = { version = "^0.11", features = [ "serde" ] }
serde = "^1.0.70"
serde_derive = "^1.0.70"
serde_json = "^1.0.22"
smart-default = "^0.6"
structopt = "^0.3"
tar = "^0.4.16"
tokio = { version = "0.2.11", features = [ "fs", "stream" ] }
toml = "^0.5"
url = "^2.2"
parking_lot = "^0.11"
tempfile = "^3.1.0"
async-trait = "^0.1"
custom_debug_derive = "^0.5"
opentelemetry = "0.4.0"
actix-service = "1.0.0"

[build-dependencies]
built = { version = "^0.4", features = [ "git2" ] }

[dev-dependencies]
twoway = "^0.2"

[features]
test-net = []
test-net-private = []
